#import <UIKit/UIKit.h>
#import <objc/runtime.h>
#import <rootless.h>
#import "libcolorpicker.h"
#import "Debug.h"


@interface SBUIController : NSObject
+(id)sharedInstance;
+(CGRect)statusBarFrameForSnapshotFrame:(CGRect)arg1 remainderFrame:(CGRect*)arg2 orientation:(long long)arg3 statusBarStyleRequest:(id)arg4 hidden:(BOOL)arg5 ;
+(CGRect)statusBarFrameForSnapshotFrame:(CGRect)arg1 orientation:(long long)arg2 statusBarStyleRequest:(id)arg3 hidden:(BOOL)arg4 ;
+(id)_effectiveStatusBarSettingsForSnapshot:(id)arg1 sceneHandle:(id)arg2 ;
+(id)sharedInstanceIfExists;
+(CGRect)statusBarFrameForDeviceApplicationSceneHandle:(id)arg1 displayConfiguration:(id)arg2 interfaceOrientation:(long long)arg3 statusBarStyleRequest:(id)arg4 withinBounds:(CGRect)arg5 inReferenceSpace:(BOOL)arg6 ;
+(id)zoomViewForDeviceApplicationSceneHandle:(id)arg1 displayConfiguration:(id)arg2 interfaceOrientation:(long long)arg3 snapshot:(id)arg4 snapshotSize:(CGSize)arg5 statusBarDescriptor:(id)arg6 decodeImage:(BOOL)arg7 hasOrientationMismatchForClassicApp:(BOOL)arg8 customContainerBounds:(CGRect)arg9 ;
-(void)accessoryEndpointDetached:(id)arg1 forConnection:(id)arg2 ;
-(void)connectedDevicesDidChange:(id)arg1 ;
-(void)accessoryEndpointAttached:(id)arg1 transportType:(int)arg2 protocol:(int)arg3 properties:(id)arg4 forConnection:(id)arg5 ;
-(void)zStackParticipantDidChange:(id)arg1 ;
-(void)cancelInProcessAnimations;
-(void)cancelVolumeEvent;
-(BOOL)homeScreenAutorotatesEvenWhenIconIsDragging;
-(void)ACPowerChanged;
-(void)setAllowIconRotation:(BOOL)arg1 forReason:(id)arg2 ;
-(void)nudgeIconInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(void)setHomeScreenAutorotatesEvenWhenIconIsDragging:(BOOL)arg1 ;
-(void)setHomeScreenScale:(double)arg1 behaviorMode:(long long)arg2 completion:(/*^block*/id)arg3 ;
-(void)handleDidEndReachabilityAnimation;
-(long long)interfaceOrientationForWallpaperController:(id)arg1 ;
-(void)disableAnimationForNextIconRotation;
-(void)accessoryEndpointInfoPropertyChanged:(id)arg1 properties:(id)arg2 forConnection:(id)arg3 ;
-(id)window;
-(void)endRequiringLiveBackdropViewForReason:(id)arg1 ;
-(void)didDetectDeviceMotion;
-(BOOL)isConnectedToChargeIncapablePowerSource;
-(void)beginRequiringLiveBackdropViewForReason:(id)arg1 ;
-(BOOL)isHeadsetBatteryCharging;
-(void)suppressChimeForConnectedPowerSources;
-(BOOL)chargingChimeEnabled;
-(void)beginRequiringBackdropViewForReason:(id)arg1 ;
-(void)_removeSuppressedAccessory:(id)arg1 ;
-(void)setHomeScreenAlpha:(double)arg1 behaviorMode:(long long)arg2 completion:(/*^block*/id)arg3 ;
-(void)endRequiringBackdropViewForReason:(id)arg1 ;
-(void)statusBarOverridesDidChange:(id)arg1 ;
-(void)interactionProgressDidUpdate:(id)arg1 ;
-(void)_playAccessoryChimeIfAppropriateForAccessory:(id)arg1 attaching:(BOOL)arg2 withDelay:(double)arg3 ;
-(void)restoreContentWithOptions:(unsigned long long)arg1 ;
-(void)windowedAccessoryPresented;
-(void)removeDetachedAccessory:(id)arg1 ;
-(void)zStackParticipant:(id)arg1 updatePreferences:(id)arg2 ;
-(void)_disableWirelessChargingChimeAndScreenWakeForDuration:(double)arg1 ;
-(void)interactionProgress:(id)arg1 didEnd:(BOOL)arg2 ;
-(void)handleVolumeButtonWithType:(long long)arg1 down:(BOOL)arg2 ;
-(id)_legibilitySettings;
-(void)storeAttachedAccessory:(id)arg1 ;
-(void)_setConnectedToWindowedAccessory:(BOOL)arg1 ;
-(void)beginRequiringContentForReason:(id)arg1 options:(unsigned long long)arg2 ;
-(id)workflowClientFromWebClip:(id)arg1 appToLaunch:(id)arg2 ;
-(int)batteryCapacityAsPercentage;
-(BOOL)handleHomeButtonDoublePressDown;
-(BOOL)isConnectedToQiPower;
-(BOOL)isHeadsetDocked;
-(void)restoreContentAndUnscatterIconsAnimated:(BOOL)arg1 withCompletion:(/*^block*/id)arg2 ;
-(void)windowedAccessoryDismissed;
-(id)init;
-(void)setHomeScreenBlurProgress:(double)arg1 behaviorMode:(long long)arg2 completion:(/*^block*/id)arg3 ;
-(void)_storeSuppressedAccessory:(id)arg1 ;
-(id)descriptionWithMultilinePrefix:(id)arg1 ;
-(BOOL)_blocksAnimationForAccessoryType:(long long)arg1 ;
-(id)contentView;
-(void)wallpaperDidChangeForVariant:(long long)arg1 ;
-(BOOL)_treatsAccessoryAsSupported:(id)arg1 ;
-(BOOL)isConnectedToWirelessInternalChargingAccessory;
-(void)_willRevealOrHideContentView;
-(void)setPointerInteractionsEnabled:(BOOL)arg1 ;
-(void)tearDownIconListAndBar;
-(void)activateApplication:(id)arg1 fromIcon:(id)arg2 location:(id)arg3 activationSettings:(id)arg4 actions:(id)arg5 ;
-(void)_setupHomeScreenDimmingWindow;
-(void)_accessoryEndpointAttached:(id)arg1 ;
-(void)_enumeratePowerSourcesWithBlock:(/*^block*/id)arg1 ;
-(void)possiblyWakeForPowerStatusChangeWithUnlockSource:(int)arg1 ;
-(BOOL)_shouldShowAnimationForAccessory:(id)arg1 ;
-(void)setHomeScreenDimmingAlpha:(double)arg1 behaviorMode:(long long)arg2 completion:(/*^block*/id)arg3 ;
-(CGRect)visibleScreenCoordinatesForWindowedAccessory;
-(void)homeScreenBackdropView:(id)arg1 opaquenessDidChange:(BOOL)arg2 ;
-(void)playChargingChimeIfAppropriate;
-(void)_activateWorkspaceEntity:(id)arg1 fromIcon:(id)arg2 location:(id)arg3 validator:(/*^block*/id)arg4 ;
-(void)_switchToHomeScreenWallpaperAnimated:(BOOL)arg1 ;
-(BOOL)isFullyCharged;
-(void)dealloc;
-(void)_activateApplicationFromAccessibility:(id)arg1 ;
-(void)noteStatusBarHeightChanged:(id)arg1 ;
-(float)batteryCapacity;
-(id)succinctDescription;
-(void)_preferredContentSizeDidChange:(id)arg1 ;
-(void)endRequiringContentForReason:(id)arg1 ;
-(void)setLockScreenScale:(double)arg1 withDuration:(double)arg2 behaviorMode:(long long)arg3 completion:(/*^block*/id)arg4 ;
-(id)scalingView;
-(void)_disableWirelessChargingChimeAndScreenWakeForDuration:(double)arg1 withMotionAlarm:(BOOL)arg2 ;
-(BOOL)isBatteryCharging;
-(void)_updateRequireWallpaperRasterization;
-(void)_dismissAccessory:(id)arg1 playChime:(BOOL)arg2 ;
-(id)_currentHomeScreenLegibilitySettings;
-(BOOL)isConnectedToWirelessInternalCharger;
-(void)wallpaperLegibilitySettingsDidChange:(id)arg1 forVariant:(long long)arg2 ;
-(void)_setAccessoryAttachmentAnimationBlockingTimerWithDuration:(double)arg1 ;
-(void)_setDebounceWirelessChargingTimerWithDuration:(double)arg1 ;
-(void)restoreContentAndUnscatterIconsAnimated:(BOOL)arg1 ;
-(void)setHomeScreenBackdropBlurMaterialRecipeName:(id)arg1 behaviorMode:(long long)arg2 completion:(/*^block*/id)arg3 ;
-(void)_removeReachabilityEffectViewIfNecessary;
-(BOOL)hasVisibleAlertItemOrSheet:(out BOOL*)arg1 ;
-(BOOL)isConnectedToUnsupportedChargingAccessory;
-(void)setIsConnectedToUnsupportedChargingAccessory:(BOOL)arg1 ;
-(BOOL)isConnectedToWirelessInternalAccessory;
-(BOOL)_isConnectedToWirelessCharging;
-(void)_accessoryEndpointDetached:(id)arg1 ;
-(BOOL)handleHomeButtonSinglePressUpForWindowScene:(id)arg1 ;
-(BOOL)_isAppropriateToReactToAccessoryEvent;
-(void)_cancelDebounceWirelessChargingTimer;
-(id)succinctDescriptionBuilder;
-(BOOL)handleHomeButtonSinglePressUpForWindowScene:(id)arg1 withSourceType:(unsigned long long)arg2 ;
-(id)descriptionBuilderWithMultilinePrefix:(id)arg1 ;
-(void)_setupHomeScreenContentBackdropView;
-(unsigned char)headsetBatteryCapacity;
-(void)_hideKeyboard;
-(void)_closeOpenFolderIfNecessary;
-(void)beginRequiringContentForReason:(id)arg1 ;
-(BOOL)_shouldInitiateAnimationForAccessory:(id)arg1 ;
-(NSString *)description;
-(BOOL)_powerSourceWantsToPlayChime;
-(void)_updateLegibility;
-(BOOL)disableAppSwitchForcePressDueToHomeButtonForce;
-(BOOL)isConnectedToExternalChargingSource;
-(void)_accessibilityWillBeginAppSwitcherRevealAnimation;
-(void)restoreContent;
-(void)_resetWirelessChargingState;
-(long long)transitionSourceForIcon:(id)arg1 iconLocation:(id)arg2 ;
-(void)setChargingChimeEnabled:(BOOL)arg1 ;
-(void)_backgroundContrastDidChange:(id)arg1 ;
-(void)_reduceMotionStatusDidChange:(id)arg1 ;
-(BOOL)isOnAC;
-(void)_debounceWirelessChargingTimerFired;
-(void)_animationBlockingTimerFired;
-(BOOL)isIconListViewTornDown;
-(void)handleWillBeginReachabilityAnimation;
-(BOOL)dissmissAlertItemsAndSheetsIfPossible;
-(void)restoreContentAndUnscatterIconsAnimated:(BOOL)arg1 afterDelay:(double)arg2 withCompletion:(/*^block*/id)arg3 ;
-(void)settings:(id)arg1 changedValueForKey:(id)arg2 ;
-(void)updateBatteryState:(id)arg1 ;
-(BOOL)supportsDetailedBatteryCapacity;
-(void)_deviceUILocked;
-(BOOL)isBackdropVisible;
-(BOOL)isAccessoryAnimationAllowed;
-(BOOL)isConnectedToWindowedAccessory;
-(void)updateStatusBarLegibilityForWindowScene:(id)arg1 ;
-(void)setIsAccessoryAnimationAllowed:(BOOL)arg1 ;
@end